name: test
on: pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run action
        uses: ./

      - name: Run action with inputs
        uses: ./
        with:
          model: codellama
          prompt: 'Summarize code diff in bullet points:'
          token: ${{ github.token }}
